name: html-charset
version: 0.1.0
synopsis: Determine character encoding of HTML documents/fragments
category: Web
author: Hong Minhee <hong.minhee@gmail.com>
maintainer: Hong Minhee <hong.minhee@gmail.com>
copyright: (c) 2018 Hong Minhee
license: LGPL-2.1
github: dahlia/html-charset
extra-source-files:
- CHANGES.md
- README.md
description: ! >
  Please see the README.md on GitHub at
  <https://github.com/dahlia/html-charset#readme>.
ghc-options:
- -Werror
- -Wall
- -fwarn-incomplete-uni-patterns
- -fprint-explicit-kinds
dependencies:
- base >= 4.7 && < 5
- bytestring
library:
  source-dirs: src
  dependencies:
  - attoparsec >= 0.12 && < 1
  - charsetdetect-ae >= 1.1 && < 2
executables:
  html-charset:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-charset
    - optparse-applicative >= 0.14 && < 1
tests:
  doctest:
    main: doctest.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    dependencies:
    - doctest
    - doctest-discover
    - html-charset
    - QuickCheck
  hlint:
    main: hlint.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    dependencies:
    - hlint >= 2.1.7
